---
- name: Set hostname to desired value
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"
  become: true

- name: Disable swap
  command: swapoff -a
  become: true

- name: Comment swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].* swap .*)$'
    replace: '# \1'
  become: true

- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present
  become: true

- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  notify: Reload sysctl
  become: true

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  become: true

- name: Add Docker CE repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: true

- name: Install containerd
  package:
    name: containerd.io
    state: present
  become: true

- name: Create containerd config dir
  file:
    path: /etc/containerd
    state: directory
  become: true

- name: Generate default containerd config
  command: containerd config default
  register: containerd_config
  become: true

- name: Save containerd config
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_config.stdout }}"
  become: true

- name: Enable systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    line: 'SystemdCgroup = true'
  become: true

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: true
    state: restarted
  become: true

- name: Add Kubernetes repo and install tools
  block:
    - name: Add Kubernetes repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key

    - name: Install kubelet, kubeadm, kubectl
      package:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: true
        state: started
  become: true

- include_tasks: firewall_selinux.yaml